title: Random Thoughts
email: liuren6@gmail.com
description: >-
  ©️ Designed by shuq3 & An0nym6
baseurl: ""
url: ""  # 发布时应更改
github_username:  An0nym6
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
jekyll-archives:
  enabled: 
    - tags
  layout: 'archive'
  permalinks:
    tag: '/archives/tag/:name/'
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
