title: Random Thoughts
email: liuren6@gmail.com
description: >-
  ©️ Designed by shuq3 & An0nym6
baseurl: ""
url: ""  # 发布时应更改
github_username:  An0nym6
markdown: kramdown
paginate: 1
paginate_path: "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
